version: '3.8'
services:
  s-assignment:
    extends: 
      file: docker-compose.yaml
      service: s-assignment
    image: s-assignment-dev:0.0.1
    build:
      target: dev
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - .:/workspace:cached
    # keep the dev container running
    command: sleep infinity